### ISSUE TITLE
URLs not configurable by enviroment variables

### ISSUE THREAD

**Issue by 4refr0nt** [mainflux/ui#10]
See ./src/environments/environment.prod.ts
When we use UI in docker container in /mainflux/docker/docker-compose.yml we can't change LoRa Server url and other by /mainflux/.env file or global enviroments variables, defined in .bashrc or other place. Docker images always use `lora.mainflux.io`
```grafanaHome: 'http://localhost:3001/?orgId=1&kiosk',
  jaegerHome: 'http://localhost:16686/search',
  loraServer: 'http://lora.mainflux.io/#/',
  nodeRedHome: 'http://localhost:1880',
```
I'm use 0.9 version for tests

**Comment by manuio** [comment]
@4refr0nt You can change the URL in `src/environments/environment.prod.ts` file and re-build a new Docker image (`make docker_ui` from the root directory).

**Comment by 4refr0nt** [comment]
`ui` project don't include in `mainflux` main project as git submodule or addon (as lora, reader or writer addons), but main docker-compose file in `mainflux/docker` folder contain `ui` section linked with image from Docker Hub, so we can't edit `ui` source files.

**Comment by manuio** [comment]
@4refr0nt If you create a new Docker image locally and run docker-compose it will use this new image and not the one from DockerHub.

**Comment by manuio** [comment]
@4refr0nt re-open this one if something still unclear
