### ISSUE TITLE
Tracing and Grafana pages cannot be accessed

### ISSUE THREAD

**Issue by sunt89** [mainflux/ui#101]
![image](https://user-images.githubusercontent.com/20986998/87141215-56e6a480-c2d5-11ea-9178-a2e2799a6022.png)
![image](https://user-images.githubusercontent.com/20986998/87141445-9e6d3080-c2d5-11ea-8d67-b1ca93263385.png)

**Comment by manuio** [comment]
@sunt89 There is not even an explanation in this issue. Please, use Gitter for this kind of questions.
