### ISSUE TITLE
I cant register with email

### ISSUE THREAD

**Issue by mmdaz** [mainflux/ui#108]
Hey!
I am using [docker-compose.yaml](https://github.com/mainflux/ui/blob/master/docker/docker-compose.yml) file and before it I am setting the email [configs](https://github.com/mainflux/ui/blob/master/.env#L51) with my mail host. but it doesn't send an email when I register with the UI form.

**Comment by mteodor** [comment]
there is no confirmation step on users registration, if that is what are you referring.
email is sent for the purposes of reseting the password in case you've forgotten it.

**Comment by mmdaz** [comment]
So, How can I register for it?
I am registering and after trying to log in.
I got this error:

```
Oh snap!

Login/Email combination is not correct, please try again.
```

**Comment by mteodor** [comment]
Ok, there may be a problem with version of images, can you ensure that you have the latest docker images?
I've just tried a fresh start, registered user and later logged in successfully.

**Comment by mmdaz** [comment]
Yes, I am using the [docker-compose.yaml](https://github.com/mainflux/ui/blob/master/docker/docker-compose.yml) file and images of this file are the last images.

**Comment by mteodor** [comment]
anything in the logs?
can you check in browser debug console if there are any errors?

**Comment by manuio** [comment]
@mmdaz I'm not sure but it looks like an issue with your setup. I just tried and all works fine. 

Please, run from the root directory the commands `make clean` and `make run` , and try again.

**Comment by mmdaz** [comment]
Finally, I can register it!
I used this [docker-compose](https://github.com/mainflux/mainflux/blob/master/docker/docker-compose.yml) file with little changes that I added the UI container to it and changed the Nginx configurations for serving and proxy passing requests to the UI and it works fine.

**Comment by manuio** [comment]
Great! I recommend you to use this one https://github.com/mainflux/ui/blob/master/docker/docker-compose.yml. But you got the idea :)
