### ISSUE TITLE
ui 405 Not Allowed

### ISSUE THREAD

**Issue by mykiya** [mainflux/ui#129]
POST /users HTTP/1.1" 405 576 " /auth/register

**Comment by mykiya** [comment]
When I create a ui service with the latest master branch, the users and tokens API remind me '405 Not Allowed' when registering account.

**Comment by manuio** [comment]
@mykiya Are you also using latest Things and Users Mainflux services?

**Comment by mykiya** [comment]
@manuio Yes, the image ID: mainflux/things(ID: c0850bd6b78f)  mainflux/users(ID: ea1748cac5a8)  nginx:1.16.0-alpine(ef04b00b089d)

**Comment by manuio** [comment]
@mykiya this does not mean that you are using latest. Please do `docker pull mainflux/things` and `docker pull mainflux/users` and try again.

**Comment by manuio** [comment]
@mykiya It's working? Can we close the issue?
