### ISSUE TITLE
UI+Lora configuration

### ISSUE THREAD

**Issue by 4refr0nt** [mainflux/ui#13]
Please, give me example nginx and ui configuration with Mainflux+Lora+UI
How to configure nginx in main mainflux project for proxing and url rewriting additional microservices (reader, writer, bootstrap and so on) for manage lora GW and devices over UI.
I successfully manage non-lora devices, but I have many troubles with lora GW and devices.
With my config I have many errors in browser console and in HTTP req logs.
```
       location ~ ^/(reader) {
            include snippets/proxy-headers.conf;
            rewrite /reader/(.*) /$1 break;
            proxy_pass http://mainflux.example.com:8905;
        }

        location ~ ^/(writer) {
            include snippets/proxy-headers.conf;
            rewrite /writer/(.*) /$1 break;
            proxy_pass http://mainflux.example.com:8900;
        }

        location ~ ^/(config) {
            include snippets/proxy-headers.conf;
            rewrite /config/(.*) /things/configs/$1 break;
            proxy_pass http://mainflux.example.com:8202;
        }

        location ~ ^/(bootstrap) {
            include snippets/proxy-headers.conf;
            rewrite /bootstrap/(.*) /things/bootstrap/$1 break;
            proxy_pass http://mainflux.example.com:8202;
        }
```

**Comment by manuio** [comment]
@4refr0nt I'm not sure to understand your question. You can't manage LoRa GW from Mainflux. You must connect them to your [ChirpStack Server](https://www.chirpstack.io/) (the project was previously called `Lora Server`), configure this [MF_LORA_ADAPTER_MESSAGES_URL](https://github.com/mainflux/mainflux/blob/master/.env#L96) ENVAR with the address of your ChirpStack MQTT Broker and finally run the docker composition of `lora-adapter`.
From UI side this environment variable `loraServer: 'http://lora.mainflux.io/#/'` refers to the [ChirpStack UI](https://www.chirpstack.io/application-server/overview/) and not to the address of the message broker. 

This [doc](https://mainflux.readthedocs.io/en/latest/lora/) can maybe help you.

**Comment by 4refr0nt** [comment]
I'm already read this doc and configure my mainflux as documented (ChirpStack server running, ENV VAR setted and put in system profile, profile activated for current user, and lora adapter started). Also, I'm cloned UI project and set proper urls in `environmens.prod.ts` and rebuld docker images, but I have some troubles with UI.
For reproduce this issue try install mainflux on clear VM (without saved docker images and volumes with previous data) and run as documented with ChirpStack server. Try open browser on other host (mainflux UI link).
1. UI make GET http req with unproper url mainflux_host://things/version
(proper links we can see in `mainflux/things/swagger.yml`)
![screen1](https://i.ibb.co/zSQyqFt/1.png "screen1")

2.UI make GET http req mainflux_host://reader/channels/xxx/messages?offset=0&limit=500
but any reader not running and nginx redirects not configured in main docker/nginx folder.
Mainflux_host nginx return root UI page for this req :)
![screen2](https://i.ibb.co/ZBCW9zR/2.png "screen2")

3. Other undefined GET req by UI for unstarted microservices (mainflux_host nginx return root UI page):
- /config
- /writer
- /bootstrap

**Comment by manuio** [comment]
@4refr0nt Thank you for the details, I understand your issue now. The problem is that we are using Nginx as proxy and it expect to find all services up and running otherwise it crash... That's why the configuration is only made for Core services.
This UI is using addons (reader, writer and boostrap) and it needs a specific configuration of the proxy:
```
    location /config {
        proxy_pass http://localhost:8202/things/configs;
    }
    location /bootstrap {
        proxy_pass http://localhost:8202/things/bootstrap;
    }
    location /reader/channels {
        proxy_pass http://localhost:8905/channels;
    }
    location /writer/channels {
        proxy_pass http://localhost:8185/channels;
    }
```
Let's think about how to document this in this repo or if we add a whole new config of docker-compose and Nginx.

**Comment by 4refr0nt** [comment]
Thanks!
