### ISSUE TITLE
Consider replacing ng2-smart-table by a custom one

### ISSUE THREAD

**Issue by darkodraskovic** [mainflux/ui#141]
The ng2-smart-table does not have a great paging capabilities. We need a better paging.

**Comment by mteodor** [comment]
maybe this can help
https://stackoverflow.com/questions/44669968/ng2-smart-table-with-paging-from-back-end-spring/55606968#55606968

**Comment by manuio** [comment]
Use the new custom table to replace ng2-smart-table:
* Custom table added here: https://github.com/mainflux/ui/pull/166
* Limit/pagination done here: https://github.com/mainflux/ui/pull/167

**Comment by manuio** [comment]
Replaced in Things, Channels and Twins tables here: https://github.com/mainflux/ui/pull/168

**Comment by manuio** [comment]
This issue will be continued here: https://github.com/mainflux/ui/issues/174
