### ISSUE TITLE
Remove redundant space from table fields and downsize buttons

### ISSUE THREAD

**Issue by darkodraskovic** [mainflux/ui#144]
We need a more elegant, minimalistic UI. Currently, there is too much margin and padding space around items. Also, buttons are too big and take too much real estate. This is not in accord with the possible huge number of list items as well as with the lean philosophy.

**Comment by manuio** [comment]
This should be solved with the custom table component. Closing this one in favour to: https://github.com/mainflux/ui/issues/141
