### ISSUE TITLE
UI run, create user fail

### ISSUE THREAD

**Issue by liuxiaodong528** [mainflux/ui#157]
hello，I have some questions and need your help

git clone https://github.com/mainflux/ui.git
cd ui
make run

1：
~$ ./mainflux-cli users token admin@example.com 12345678
failed to create entity : 400 Bad Request

DockerLog：
mainflux-users     | {"level":"warn","message":"Method login for user admin@example.com took 75.804202ms to complete with error: non-existent user : rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:8181: connect: connection refused\".","ts":"2021-01-04T14:20:43.031733633Z"}

2：
~$ ./mainflux-cli users create test@example.com 12345678
ok

DockerLog：
mainflux-users     | {"level":"info","message":"Method register for user test@example.com took 76.595137ms to complete without errors.","ts":"2021-01-04T14:22:18.521393154Z"}

3：
~$ ./mainflux-cli users token test@example.com 12345678
failed to create entity : 400 Bad Request

DockerLog：
mainflux-users     | {"level":"warn","message":"Method login for user test@example.com took 76.659355ms to complete with error: non-existent user : rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:8181: connect: connection refused\".","ts":"2021-01-04T14:22:33.533178126Z"}

**Comment by drasko** [comment]
@liuxiaodong528 thanks for reporting, @manuio will take a look into this.

**Comment by liuxiaodong528** [comment]
Thank you, this problem has been solved; now it can run normally;

**Comment by manuio** [comment]
@liuxiaodong528 The issue will be closed once it's merged in the master.

**Comment by liuxiaodong528** [comment]
@manuio ok
