### ISSUE TITLE
Connect thing to channel

### ISSUE THREAD

**Issue by ChiQuang98** [mainflux/ui#199]
I can not connect a thing to a channel in UI interface. nothing show up to click channel to connect
![{D20E6DF1-225E-41DD-967E-842639D0078E} png](https://user-images.githubusercontent.com/35691187/112416753-e3989c00-8d58-11eb-8d28-0b4b8011a30a.jpg)

**Comment by manuio** [comment]
@ChiQuang98 We recently introduced some breaking changes by inverting the logic around connections lists.  I propose you to pull latest `ui` and `things` images with `docker pull mainflux/ui && docker pull mainflux/things` and retry.
