### ISSUE TITLE
missing or invalid bearer user token 401 Unauthorized

### ISSUE THREAD

**Issue by Immanuel-Licht** [mainflux/ui#251]
Hi
I followed the instructions to do, but it's failed, using the mainflux-cli also get the same result.
![image](https://user-images.githubusercontent.com/29625478/162679942-a92c4a20-ab99-40d2-a02f-16a205e8fdb4.png)
![image](https://user-images.githubusercontent.com/29625478/162681626-acd5d3b0-b79e-456a-9440-fe3c05116910.png)
Is there any other configuration or step I haven't done?
Thanks.

**Comment by mteodor** [comment]
can you try following
export token='Bearer eyJhBGci0.....`

**Comment by Immanuel-Licht** [comment]
Thanks for your reply.
I tried it but didn't work. I want to quickly learn about mainflux through  UI , I used make run, it can login normally but didn't have permission to get Things or Channels info.
![image](https://user-images.githubusercontent.com/29625478/162698706-a58960ff-3278-4b89-b852-bf588814b03a.png)

**Comment by mteodor** [comment]
are you on the latest version?
can you check version with 
```

**Comment by manuio** [comment]
@Immanuel-Licht The UI image is from 4 month ago. Update it and it should work since we recently fixed this. We will release 0.13 ASAP and we will create proper tags to don't have this kind of issues.

**Comment by Immanuel-Licht** [comment]
Ok, I’ll try.Thanks! @mteodor @manuio

**Comment by manuio** [comment]
@Immanuel-Licht It's working? Can we close the issue?

**Comment by Immanuel-Licht** [comment]
Yes,it’s went well.👍I close the issue.
