### ISSUE TITLE
Can't login to Mainflux admin UI

### ISSUE THREAD

**Issue by McCarou** [mainflux/ui#280]
Good day!
Have the problem with login on the screen. Briefly, it says, it can't find `/tokens` endpoint

I deployed mainflux localy with the following configurations:
- Ubuntu 22.04.2 LTS
- Docker Version 24.0.2 
- Docker Compose version v2.10.2
- libprotoc 3.19.1

The log is also attached.
[log.txt](https://github.com/mainflux/ui/files/12050034/log.txt)

Will be grateful for your help.

![image](https://github.com/mainflux/ui/assets/12096852/0fd80a12-4378-47c7-a2b7-17195403d9e4)

**Comment by yinlonglyl** [comment]
I had the same problem, I think this ui repository code is behind mainflux main repository after checking the mainflux/users code. The '/tokens' endpoint is not exist in 'mainflux\users\api\clients.go', the latest endpoint is '/users/tokens/issue'.
Please check this doc(https://docs.mainflux.io/api/) for the latest API usage.

**Comment by dborovcanin** [comment]
Hello @McCarou, @yinlonglyl , this is an obsolete version of the Mainflux UI that will be archived soon. Please use CLI tool instead.
