### ISSUE TITLE
Error 200 - OK and Can't login

### ISSUE THREAD

**Issue by longlnk** [mainflux/ui#98]
I use UI version 0.10.0 and 0.11.0 run on rancher/k8s
1. I can't login after register account
2. Login IP:port/ then error on below
![image](https://user-images.githubusercontent.com/15074179/84846745-a42a7a00-b079-11ea-87c4-e0716ecff968.png)
![image](https://user-images.githubusercontent.com/15074179/84847510-878f4180-b07b-11ea-8f3e-76a9f6ed823d.png)

The information mainlux which I installed on Rancher
![image](https://user-images.githubusercontent.com/15074179/84846875-f8cdf500-b079-11ea-95c3-6fda93dd56bc.png)

Please help me.

**Comment by manuio** [comment]
@longlnk UI version 0.10.0 is not compatible with Mainflux 0.11.0. Please, use the new release that we just created: https://github.com/mainflux/ui/releases/tag/v0.11.0

**Comment by manuio** [comment]
Closing this one

**Comment by longlnk** [comment]
Hi,

- I use mainflux v0.11.0 and I used UI version 0.11.0 and latest, but I can't login.

![image](https://user-images.githubusercontent.com/15074179/89716326-2aa66c80-d9d6-11ea-9128-24c9b9083904.png)

![image](https://user-images.githubusercontent.com/15074179/89716335-414cc380-d9d6-11ea-99a4-916dcafbae8d.png)

![image](https://user-images.githubusercontent.com/15074179/89716353-6c371780-d9d6-11ea-98f4-64a7c6746701.png)

Please help me.
